result = ' /-\ '.center(7)
print(result)
result = '//_\\\\'.center(7)
print(result)
result = '-------'.center(7)
print(result)
result = '\\\\_//'.center(7)
print(result)
result = '\_/'.center(7)
print(result)

print()
print()
print('----' .center(8))
print('/      \\' .center(8))
print('/______\\' .center(8))

print()
print()
print("*".center(8))
print("***".center(8))
print("*****".center(8))
print("*******")

